### PR TITLE
New York Times Article

### PR DESCRIPTION
**Pull request by OmarRamoun**
## Changes
- Create a header
- Create an article
- Create Editor's Picks section
- Create Footer Section

### CODE REVIEW

**Comment by wathigo** [comment]
> ### The submission has been marked as Invalid since all linter checks are not passing.
> ### Make sure that all checks are passing before submitting the project.

**SIMON WATHIGO**

**Comment by OmarRamoun** [comment]
## Incase: 

- if some images didn't load, just reload the page and make sure to view the page from this [link](https://mrramoun.github.io/NYT-Article-Clone/).
> **Note**: Some fonts will take some time to load.

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @MrRamoun  :wave:

__You've done well so far :clap:__

- Project looks good :ok_hand: 
- Commit messages are well composed :ok:
- You paid attention to the details of this project. Keep it up! 

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] Kindly add contents to the `Getting Started` section of your Readme. This section should contain the step-by-step process of cloning and using your app. 
- [ ] The `Issues page` and `MIT license` links are broken. Please generate an MIT license file and commit it to your project. Also, ensure that all links in your Readme are working.
- [x] Your pull request (PR) title is not suitable enough. Titles like `New York Times Article`, `NYT - Clone feature`, or similar can be used.
- [x] Also, your PR description does not summarize all you did in this PR. You only said `Finish the whole webpage`, however, this can be restructured to form a better summary suitable for your project.

**[ OPTIONAL CHANGES ]**

- [x] It looks like you're using a lot of SVG icons. To make your HTML code readable and maintainable, I'll suggest you extract your SVG icons into a separate file, then store it in your assets folder so that you can use it with an image tag in your HTML. 

* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by MahmoudBakr23 — APPROVED** [review]
# **Approved ✔✔**

<hr>

Hello there, congratulations on doing the requested changes. Your cloned project looks just perfect. Great job, and you may now merge to the master and submit 🎉🎉👍👍

Good luck with the next and always happy coding 👨‍💻💻

**Pull request merged**
